### ISSUE TITLE
Add video wrapper object

### ISSUE THREAD

**Issue by philbuchanan** [philbuchanan/WordPress-Theme-Skeleton#151]
```scss
// 1. Set to 16:9 aspect ratio
.o-video-wrapper {
	position: relative;
	margin-bottom: $global-spacing-unit;
	padding-bottom: 56.25%; // [1]
	height: 0;

	iframe {
		position: absolute;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
	}

	p {
		margin-bottom: 0; // 2. Remove default margin from paragraphs
	}
}
```
