### ISSUE TITLE
Add disabled button styles

### ISSUE THREAD

**Issue by philbuchanan** [philbuchanan/WordPress-Theme-Skeleton#176]
With this CSS:

```css
[disabled] {
	pointer-events: none;
	opacity: 0.6;
}
```
